# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Scrape-USPS-ZipLookup
version:      2.3
version_from: lib/Scrape/USPS/ZipLookup.pm
installdirs:  site
requires:
    WWW::Mechanize:                0.7

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
